name: khdmti_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3
  flutter_test:
    sdk: flutter
  go_router: ^17.1.0
  image_picker: ^1.2.1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  permission_handler: ^11.3.1
  cached_network_image: ^3.4.1
  supabase_flutter: ^2.12.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: IBMPlexSansArabic
      fonts:
        - asset: assets/font/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Thin.ttf
          weight: 100
        - asset: assets/font/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-ExtraLight.ttf
          weight: 200
        - asset: assets/font/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Light.ttf
          weight: 300
        - asset: assets/font/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Regular.ttf
          weight: 400
        - asset: assets/font/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Medium.ttf
          weight: 500
        - asset: assets/font/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-SemiBold.ttf
          weight: 600
        - asset: assets/font/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Bold.ttf
          weight: 700

dev_dependencies:
    flutter_lints: ^6.0.0
